apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: default
  labels:
    app: discord-store-website
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: discord-store-website
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
