apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: discord-store-gateway
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: discord-store-gateway
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
